#ifndef EXP_CONVEX_COST_MANAGER_HPP
#define EXP_CONVEX_COST_MANAGER_HPP

#include "traj_opt/convex_hull/continuous_certificate.hpp"
#include "traj_opt/convex_hull/convex_hull.hpp"
#include "traj_opt/convex_hull/flatness_convex_hull_cost.hpp"
#include "traj_opt/convex_hull/scalar_bernstein.hpp"
#include "traj_opt/costfunctional/spatialcosts/polytope_position_penalty.hpp"
#include "traj_opt/costfunctional/spatialcosts/squared_norm_bound_penalty.hpp"
#include "traj_opt/costfunctional/spatialcosts/way_point_attractor_penalty.hpp"
#include "traj_opt/costfunctional_manager/exp_integal_cost_manager.hpp"
#include "traj_opt/solver_quality_report.hpp"

#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <limits>
#include <vector>

namespace cost_functional_manager
{
/**
 * State2state corridor cost manager using a control-point cost functional.
 *
 * Every source segment is converted to subdivided Bezier position controls
 * exactly once. Physical-time derivative controls are then generated by the
 * Bezier hodograph recurrence
 *
 *   B_i^(r) = (n-r+1) / T_leaf * (B_(i+1)^(r-1)-B_i^(r-1)).
 *
 * The adjoint follows the same difference chain in reverse, so position,
 * velocity, acceleration and jerk costs require one power-to-Bezier operator
 * and one final MINCO coefficient adjoint. MINVO costs are obtained by a small
 * degree-local Bezier-to-MINVO basis change after the hodograph; they do not
 * trigger independent source-polynomial conversions.
 *
 * Non-polynomial costs (guide path, swarm) retain the original dense
 * evaluator. Angular-rate / thrust can be moved onto the continuous flatness
 * convex-hull certificate; then MINCOOptimizer skips dense sampling entirely
 * when guide/swarm are also inactive.
 */
class ExpConvexCostManager
{
public:
  using Basis = traj_opt::convex_hull::Basis;
  using FlatnessCost = traj_opt::convex_hull::FlatnessConvexHullCost;

  struct EvaluatorTiming
  {
    double transform_seconds{0.0};
    double hodograph_seconds{0.0};
    double position_residual_seconds{0.0};
    double derivative_residual_seconds{0.0};
    double reverse_hodograph_seconds{0.0};
    double backward_add_seconds{0.0};
    double discrete_attractor_seconds{0.0};
  };

  void configure(Basis basis,
                 int subdivision_depth,
                 double position_scale = 0.25,
                 double robust_certificate_margin = 0.05)
  {
    basis_ = basis;
    subdivision_depth_ = std::clamp(subdivision_depth, 0, 8);
    // Production route: fixed depth only. Bezier always uses the algebraically
    // equivalent V2 endpoint-deduplicated functional; MINVO has one native
    // control-point functional.
    position_scale_ = std::max(1.0e-6, position_scale);
    robust_certificate_margin_ = std::max(0.0, robust_certificate_margin);
    // Flatness hull requires fixed-depth Bezier hodograph controls.
    if (basis_ != Basis::Bezier)
    {
      flatness_enabled_ = false;
      flatness_advisory_only_ = false;
      flatness_cost_.clearReference();
    }
  }

  /**
   * Flatness envelope on hodograph controls. Exact FlatnessMap penalties
   * remain in the real objective. Production config uses advisory_only=true
   * until the angular-rate envelope has a rigorous Bernstein construction.
   */
  void configureFlatness(bool enabled,
                         const FlatnessCost::Config &config,
                         bool advisory_only = false)
  {
    flatness_enabled_ = enabled && basis_ == Basis::Bezier;
    flatness_advisory_only_ = flatness_enabled_ && advisory_only;
    flatness_cost_.configure(config);
    if (!flatness_enabled_)
    {
      flatness_advisory_only_ = false;
      flatness_cost_.clearReference();
    }
  }

  bool usesFlatnessHull() const { return flatness_enabled_; }
  bool flatnessAdvisoryOnly() const
  {
    return flatness_enabled_ && flatness_advisory_only_;
  }
  const FlatnessCost::Config &flatnessConfig() const
  {
    return flatness_cost_.config();
  }

  const FlatnessCost::Diagnostics &flatnessDiagnostics() const
  {
    return flatness_cost_.diagnostics();
  }

  template <typename Trajectory>
  void refreshFlatnessReference(const Trajectory &trajectory)
  {
    if (!flatness_enabled_ || !ready())
    {
      flatness_cost_.clearReference();
      return;
    }
    updateControlPoints(trajectory);
    refineFlatnessCertificateControls();
    flatness_cost_.refreshReference(
        trajectory,
        bezier_hull_.numSourceSegments() *
            flatness_certificate_leaves_per_segment_,
        flatness_certificate_leaves_per_segment_,
        flatness_certificate_controls_[1],
        controlsPerPiece(1),
        trajectory.getDurations());
  }

  void reset(const general_utils::PolyhedraH *h_polys,
             const Eigen::VectorXi *h_poly_idx,
             const general_utils::Mat3Df *waypoint_attractors,
             const general_utils::VecDf *waypoint_attractor_dead_d,
             double smooth_eps,
             const general_utils::VecDf &magnitude_bounds,
             const general_utils::VecDf &penalty_weights,
             flatness::FlatnessMap *quadrotor_flatness,
             const traj_opt::SwarmPenaltyConfig &swarm_config,
             const traj_opt::SwarmTrajectoriesConstPtr &swarm_trajs,
             double swarm_current_wall_time,
             const general_utils::vec_E<general_utils::Vec3f> *guide_path = nullptr,
             const std::vector<double> *guide_t = nullptr,
             double weight_guide_integral = 0.0,
             double guide_path_tube_radius = 0.0,
             double guide_path_z_tube_radius = 0.0,
             double guide_path_huber_delta = 0.0,
             bool guide_path_time_gradient_en = false,
             double weight_guide_z_lower = 0.0,
             double guide_z_lower_tolerance = 0.0)
  {
    h_polys_ = h_polys;
    h_poly_idx_ = h_poly_idx;
    smooth_eps_ = std::max(1.0e-6, smooth_eps);
    magnitude_bounds_ = magnitude_bounds;
    penalty_weights_ = penalty_weights;
    waypoint_attractors_ = waypoint_attractors;
    waypoint_attractor_dead_d_ = waypoint_attractor_dead_d;

    // Phase 0: keep attractor as a discrete junction cost so it no longer
    // forces the full dense integral loop. Residual dense only covers
    // non-polynomial terms (guide/swarm, and omg/thrust when flatness hull
    // is off).
    general_utils::VecDf residual_weights = penalty_weights;
    const int polynomial_weight_count =
        std::min<int>(4, residual_weights.size());
    residual_weights.head(polynomial_weight_count).setZero();
    if (residual_weights.size() > 4)
    {
      residual_weights(4) = 0.0;
    }
    residual_cost_manager_.reset(h_polys,
                                 h_poly_idx,
                                 nullptr,
                                 nullptr,
                                 smooth_eps,
                                 magnitude_bounds,
                                 residual_weights,
                                 quadrotor_flatness,
                                 swarm_config,
                                 swarm_trajs,
                                 swarm_current_wall_time,
                                 guide_path,
                                 guide_t,
                                 weight_guide_integral,
                                 guide_path_tube_radius,
                                 guide_path_z_tube_radius,
                                 guide_path_huber_delta,
                                 guide_path_time_gradient_en,
                                 weight_guide_z_lower,
                                 guide_z_lower_tolerance);

    discrete_attractor_active_ =
        penalty_weights_.size() > 4 && penalty_weights_(4) > 0.0 &&
        waypoint_attractors_ != nullptr &&
        waypoint_attractor_dead_d_ != nullptr;
    const bool angular_rate_active =
        residual_weights.size() > 5 &&
        residual_weights(5) > 0.0;
    const bool thrust_active =
        residual_weights.size() > 6 &&
        residual_weights(6) > 0.0;
    const bool guide_active = weight_guide_integral > 0.0 ||
                              weight_guide_z_lower > 0.0;
    const bool swarm_active =
        swarm_trajs != nullptr &&
        ((swarm_config.enable && swarm_config.weight > 0.0) ||
         (swarm_config.formation_enable &&
          swarm_config.formation_weight > 0.0));
    dense_sampling_required_ = angular_rate_active || thrust_active ||
                               guide_active || swarm_active;
    flatness_cost_.clearReference();
    last_scalar_constraint_checks_ = 0;
    last_evaluator_timing_ = EvaluatorTiming{};
  }

  std::size_t lastScalarConstraintChecks() const
  {
    return last_scalar_constraint_checks_;
  }

  const EvaluatorTiming &lastEvaluatorTiming() const
  {
    return last_evaluator_timing_;
  }

  double positionScale() const { return position_scale_; }

  double robustCertificateMargin() const
  {
    return robust_certificate_margin_;
  }

  bool usesDenseSampling() const
  {
    return dense_sampling_required_;
  }

  bool usesSampleCost() const
  {
    return residual_cost_manager_.usesSampleCost();
  }

  std::size_t activeControlPointChecksPerEvaluation() const
  {
    if (last_coarse_screen_only_)
    {
      std::size_t checks = 0;
      for (int derivative_order = 0; derivative_order <= 3;
           ++derivative_order)
      {
        if (penalty_weights_.size() > derivative_order &&
            penalty_weights_(derivative_order) > 0.0)
        {
          checks += static_cast<std::size_t>(
              levels_[0].hull.numSourceSegments() *
              (levels_[0].hull.sourceDegree() + 1 - derivative_order));
        }
      }
      return checks;
    }
    if (!bezier_hull_.kernel())
    {
      return 0;
    }
    std::size_t checks = 0;
    for (int derivative_order = 0; derivative_order <= 3;
         ++derivative_order)
    {
      if (penalty_weights_.size() > derivative_order &&
          penalty_weights_(derivative_order) > 0.0)
      {
        if (basis_ == Basis::Bezier)
        {
          const int cp = controlsPerPiece(derivative_order);
          const int unique_per_segment =
              bezier_hull_.piecesPerSegment() * (cp - 1) + 1;
          checks += static_cast<std::size_t>(
              bezier_hull_.numSourceSegments() * unique_per_segment);
        }
        else
        {
          checks += static_cast<std::size_t>(
              selected_controls_[derivative_order].rows());
        }
      }
    }
    return checks;
  }

  void beginEvaluation(const std::vector<double> *times)
  {
    residual_cost_manager_.beginEvaluation(times);
    hull_violation_.setZero(9);
  }

  const general_utils::VecDf &getPenaltyLog() const
  {
    combined_penalty_log_ = residual_cost_manager_.getPenaltyLog();
    if (combined_penalty_log_.size() < hull_violation_.size())
    {
      combined_penalty_log_.conservativeResize(hull_violation_.size());
    }
    for (int i = 1; i <= 4; ++i)
    {
      combined_penalty_log_(i) =
          std::max(combined_penalty_log_(i), hull_violation_(i));
    }
    // sampled_feasible describes the real FlatnessMap residual grid. Keep the
    // post-solve envelope diagnostics separate: merging their previous values
    // here made a shadow-certificate failure look like a sampled-model failure.
    return combined_penalty_log_;
  }

  double guideIntegralViolation() const
  {
    return residual_cost_manager_.guideIntegralViolation();
  }

  double guideZLowerViolation() const
  {
    return residual_cost_manager_.guideZLowerViolation();
  }

  double guideCostLog() const
  {
    return residual_cost_manager_.guideCostLog();
  }

  double guideMaxAbsTimeGrad() const
  {
    return residual_cost_manager_.guideMaxAbsTimeGrad();
  }

  int guideOutOfTimeRangeSamples() const
  {
    return residual_cost_manager_.guideOutOfTimeRangeSamples();
  }

  double evaluateIntegral(int logical_idx,
                          double t_local,
                          double t_global,
                          int seg_idx,
                          int step_in_seg,
                          const Eigen::Vector3d &position,
                          const Eigen::Vector3d &velocity,
                          const Eigen::Vector3d &acceleration,
                          const Eigen::Vector3d &jerk,
                          Eigen::Vector3d &grad_position,
                          Eigen::Vector3d &grad_velocity,
                          Eigen::Vector3d &grad_acceleration,
                          Eigen::Vector3d &grad_jerk,
                          double &grad_time) const
  {
    return residual_cost_manager_.evaluateIntegral(logical_idx,
                                                   t_local,
                                                   t_global,
                                                   seg_idx,
                                                   step_in_seg,
                                                   position,
                                                   velocity,
                                                   acceleration,
                                                   jerk,
                                                   grad_position,
                                                   grad_velocity,
                                                   grad_acceleration,
                                                   grad_jerk,
                                                   grad_time);
  }

  template <typename SampleBuffer>
  double evaluateSample(const SampleBuffer &samples,
                        Eigen::Matrix<double, 3, Eigen::Dynamic> &grad_position,
                        Eigen::VectorXd &grad_time) const
  {
    return residual_cost_manager_.evaluateSample(
        samples, grad_position, grad_time);
  }

  template <typename Trajectory>
  double evaluateCoefficient(
      const Trajectory &trajectory,
      typename Trajectory::CoeffMat &grad_coefficients,
      Eigen::VectorXd &grad_durations) const
  {
    last_scalar_constraint_checks_ = 0;
    last_evaluator_timing_ = EvaluatorTiming{};
    last_coarse_screen_only_ = false;
    if (!ready())
    {
      return 0.0;
    }

    using Clock = std::chrono::steady_clock;
    const auto t0 = Clock::now();
    double cost = 0.0;
    const bool coarse_safe =
        basis_ == Basis::Bezier &&
        allPolynomialPenaltiesProvablyZero(trajectory);
    if (coarse_safe)
    {
      // Every depth-two child control is a convex combination of these
      // depth-zero controls. Half-space and norm-bound penalties are thus
      // exactly zero; skipping them preserves the V2 objective and gradient.
      last_coarse_screen_only_ = true;
      last_scalar_constraint_checks_ =
          activeControlPointChecksPerEvaluation();
      last_evaluator_timing_.transform_seconds +=
          std::chrono::duration<double>(Clock::now() - t0).count();
    }
    else
    {
      updateControlPoints(trajectory);
      last_evaluator_timing_.transform_seconds +=
          std::chrono::duration<double>(Clock::now() - t0).count();
      const Eigen::VectorXd &durations = trajectory.getDurations();

      const auto t_pos = Clock::now();
      cost = accumulatePositionCost(durations, grad_durations);
      last_evaluator_timing_.position_residual_seconds +=
          std::chrono::duration<double>(Clock::now() - t_pos).count();
      const auto t_der = Clock::now();
      for (int derivative_order = 1; derivative_order <= 3;
           ++derivative_order)
      {
        cost += accumulateDerivativeCost(durations,
                                         derivative_order,
                                         grad_durations);
      }
      last_evaluator_timing_.derivative_residual_seconds +=
          std::chrono::duration<double>(Clock::now() - t_der).count();

      const auto t_rev = Clock::now();
      backwardControlPointGradients(durations, grad_durations);
      last_evaluator_timing_.reverse_hodograph_seconds +=
          std::chrono::duration<double>(Clock::now() - t_rev).count();
      const auto t_add = Clock::now();
      bezier_hull_.backwardAdd(bezier_gradients_[0],
                               grad_coefficients,
                               grad_durations);
      last_evaluator_timing_.backward_add_seconds +=
          std::chrono::duration<double>(Clock::now() - t_add).count();
    }

    const auto t_attr = Clock::now();
    cost += evaluateDiscreteAttractor(
        trajectory, grad_coefficients, grad_durations);
    last_evaluator_timing_.discrete_attractor_seconds +=
        std::chrono::duration<double>(Clock::now() - t_attr).count();
    return cost;
  }

  /**
   * Post-solve continuous Bezier certificate oracle. The certificate may
   * refine its private de Casteljau forest without changing the fixed
   * depth-two objective or the L-BFGS topology.
   */
  template <typename Trajectory>
  traj_opt::ContinuousCertificateReport computeContinuousCertificate(
      const Trajectory &trajectory,
      bool evaluate_flatness_advisory = true)
  {
    traj_opt::ContinuousCertificateReport report;
    if (!ready() || trajectory.getPieceNum() <= 0 || h_polys_ == nullptr ||
        h_poly_idx_ == nullptr)
    {
      return report;
    }

    traj_opt::convex_hull::CertificateOptions options;
    options.max_depth = std::max(subdivision_depth_, 4);
    options.safe_margin = robust_certificate_margin_;
    options.refine_margin = robust_certificate_margin_;
    options.coarsen_margin = robust_certificate_margin_ + 0.05;
    options.position_scale = position_scale_;
    options.certify_position =
        penalty_weights_.size() > 0 && penalty_weights_(0) > 0.0;
    options.certify_velocity =
        penalty_weights_.size() > 1 && penalty_weights_(1) > 0.0;
    options.certify_acceleration =
        penalty_weights_.size() > 2 && penalty_weights_(2) > 0.0;
    options.certify_jerk =
        penalty_weights_.size() > 3 && penalty_weights_(3) > 0.0;

    traj_opt::convex_hull::ContinuousCertificateOracle oracle;
    oracle.configure(options);
    report = oracle.certify(trajectory,
                            *h_polys_,
                            *h_poly_idx_,
                            magnitude_bounds_);

    if (flatness_enabled_ &&
        (!flatness_advisory_only_ || evaluate_flatness_advisory))
    {
      refreshFlatnessReference(trajectory);
      Eigen::MatrixXd velocity_gradients =
          Eigen::MatrixXd::Zero(flatness_certificate_controls_[1].rows(), 3);
      Eigen::MatrixXd acceleration_gradients =
          Eigen::MatrixXd::Zero(flatness_certificate_controls_[2].rows(), 3);
      Eigen::MatrixXd jerk_gradients =
          Eigen::MatrixXd::Zero(flatness_certificate_controls_[3].rows(), 3);
      flatness_cost_.accumulate(flatness_certificate_controls_[1],
                                flatness_certificate_controls_[2],
                                flatness_certificate_controls_[3],
                                bezier_hull_.numSourceSegments() *
                                    flatness_certificate_leaves_per_segment_,
                                controlsPerPiece(1),
                                controlsPerPiece(2),
                                controlsPerPiece(3),
                                velocity_gradients,
                                acceleration_gradients,
                                jerk_gradients);
      const auto &diag = flatness_cost_.diagnostics();
      report.flatness_certificate_enabled = true;
      report.flatness_advisory_only = flatness_advisory_only_;
      report.flatness_advisory_feasible = diag.certified;
      report.max_tilt_violation = diag.max_tilt_violation;
      report.max_thrust_violation =
          std::max(diag.max_thrust_upper_violation,
                   diag.max_thrust_lower_violation);
      report.max_angular_rate_violation =
          diag.max_angular_rate_violation;
      report.max_flatness_trust_violation =
          diag.max_velocity_trust_violation;
      report.max_flatness_violation = diag.maxViolation();
      if (!flatness_advisory_only_)
      {
        report.max_normalized_violation =
            std::max(report.max_normalized_violation,
                     flatness_cost_.normalizedMaxViolation());
        report.continuous_feasible =
            report.continuous_feasible && diag.certified;
        report.robustly_certified =
            report.robustly_certified && diag.certified;
        const auto &flatness_candidates =
            flatness_cost_.constraintCandidates();
        report.violated.insert(report.violated.end(),
                               flatness_candidates.begin(),
                               flatness_candidates.end());
      }
    }
    return report;
  }

private:
  using Hull = traj_opt::convex_hull::Representation<3>;
  using HullMatrix = typename Hull::Matrix;

  // Retained only for source compatibility of archived, non-instantiated
  // helper templates below. No production API can enable this route.
  struct LegacyAdaptiveOptions
  {
    bool enabled{false};
    double position_refine_margin{0.05};
    bool refine_derivative_constraints{false};
    double derivative_refine_margin{0.05};
  };

  struct LevelWorkspace
  {
    int depth{0};
    mutable Hull hull;
    mutable std::array<HullMatrix, 4> controls;
    mutable std::array<HullMatrix, 4> gradients;
  };

  bool ready() const
  {
    return h_polys_ != nullptr &&
           h_poly_idx_ != nullptr &&
           magnitude_bounds_.size() >= 3 &&
           penalty_weights_.size() >= 4;
  }

  template <typename Trajectory>
  bool allPolynomialPenaltiesProvablyZero(
      const Trajectory &trajectory) const
  {
    if (subdivision_depth_ <= 0)
    {
      return false;
    }
    updateLevel(trajectory, levels_[0]);
    for (int segment = 0; segment < trajectory.getPieceNum(); ++segment)
    {
      if (segmentNeedsFineWithLevel(
              levels_[0], segment, /*violation_only=*/true))
      {
        return false;
      }
    }
    return true;
  }

  int levelIndexForSegment(int segment) const
  {
    if (segment < 0 ||
        segment >= static_cast<int>(selected_depths_.size()) ||
        selected_depths_[static_cast<std::size_t>(segment)] == 0)
    {
      return 0;
    }
    return 1;
  }

  bool levelSelected(int level_index) const
  {
    const int depth = level_index == 0 ? 0 : subdivision_depth_;
    return std::find(selected_depths_.begin(),
                     selected_depths_.end(),
                     depth) != selected_depths_.end();
  }

  int controlsPerPiece(const LevelWorkspace &level, int order) const
  {
    return level.hull.sourceDegree() + 1 - order;
  }

  template <typename Trajectory>
  void updateLevel(const Trajectory &trajectory,
                   LevelWorkspace &level) const
  {
    const bool topology_changed =
        !level.hull.kernel() ||
        level.hull.numSourceSegments() != trajectory.getPieceNum() ||
        level.hull.sourceNumCoeffs() != Trajectory::COEFF_NUM ||
        level.hull.subdivisionDepth() != level.depth;
    if (topology_changed)
    {
      level.hull.resetTopology(trajectory.getPieceNum(),
                               Trajectory::COEFF_NUM,
                               Basis::Bezier,
                               0,
                               level.depth);
      const int pieces = level.hull.numPieces();
      for (int order = 0; order <= 3; ++order)
      {
        const int cp = controlsPerPiece(level, order);
        level.controls[order].resize(pieces * cp, 3);
        level.gradients[order].resize(pieces * cp, 3);
      }
    }

    trajectory.updateConvexHull(level.hull);
    level.controls[0] = level.hull.controls();
    const Eigen::VectorXd &durations = trajectory.getDurations();
    const int leaves = level.hull.piecesPerSegment();
    for (int order = 1; order <= 3; ++order)
    {
      const int previous_cp = controlsPerPiece(level, order - 1);
      const int current_cp = previous_cp - 1;
      const double degree_factor = static_cast<double>(previous_cp - 1);
      for (int piece = 0; piece < level.hull.numPieces(); ++piece)
      {
        const int segment = level.hull.pieceInfo(piece).source_segment;
        const double scale =
            degree_factor * static_cast<double>(leaves) /
            durations(segment);
        const int previous_row = piece * previous_cp;
        const int current_row = piece * current_cp;
        for (int control = 0; control < current_cp; ++control)
        {
          level.controls[order].row(current_row + control) =
              scale *
              (level.controls[order - 1].row(previous_row + control + 1) -
               level.controls[order - 1].row(previous_row + control));
        }
      }
    }
    for (auto &gradient : level.gradients)
    {
      gradient.setZero();
    }
  }

  template <typename Trajectory>
  void updateSelectedLevels(const Trajectory &trajectory) const
  {
    if (static_cast<int>(selected_depths_.size()) !=
        trajectory.getPieceNum())
    {
      selected_depths_.assign(
          static_cast<std::size_t>(trajectory.getPieceNum()), 0);
    }
    if (levelSelected(0))
    {
      updateLevel(trajectory, levels_[0]);
    }
    if (subdivision_depth_ > 0 && levelSelected(1))
    {
      updateLevel(trajectory, levels_[1]);
    }
  }

  bool segmentNeedsFineWithLevel(const LevelWorkspace &coarse,
                                 int segment,
                                 bool violation_only = false) const
  {
    if (subdivision_depth_ <= 0)
    {
      return false;
    }
    if (!coarse.hull.kernel())
    {
      return true;
    }
    const double position_threshold =
        violation_only ? 0.0 : -adaptive_.position_refine_margin;
    if (penalty_weights_(0) > 0.0 && segment < h_poly_idx_->size())
    {
      const int poly_id = (*h_poly_idx_)(segment);
      if (poly_id >= 0 && poly_id < static_cast<int>(h_polys_->size()))
      {
        const auto &poly = (*h_polys_)[poly_id];
        const int cp = controlsPerPiece(coarse, 0);
        const int first_row = segment * cp;
        for (int control = 0; control < cp; ++control)
        {
          const Eigen::Vector3d value =
              coarse.controls[0].row(first_row + control).transpose();
          for (int plane = 0; plane < poly.rows(); ++plane)
          {
            const double raw =
                poly.template block<1, 3>(plane, 0).dot(value) +
                poly(plane, 3);
            if (raw > position_threshold)
            {
              return true;
            }
          }
        }
      }
    }

    const double derivative_refine_threshold =
        violation_only
            ? 0.0
            : (adaptive_.refine_derivative_constraints
                   ? -adaptive_.derivative_refine_margin
                   : 0.0);
    for (int order = 1; order <= 3; ++order)
    {
      if (penalty_weights_.size() <= order ||
          penalty_weights_(order) <= 0.0)
      {
        continue;
      }
      const double bound = magnitude_bounds_(order - 1);
      if (!std::isfinite(bound) || bound <= 0.0)
      {
        continue;
      }
      const int cp = controlsPerPiece(coarse, order);
      const int first_row = segment * cp;
      for (int control = 0; control < cp; ++control)
      {
        const double normalized =
            coarse.controls[order].row(first_row + control).squaredNorm() /
                (bound * bound) -
            1.0;
        if (normalized > derivative_refine_threshold)
        {
          return true;
        }
      }
    }
    return false;
  }

  bool segmentNeedsFine(int segment) const
  {
    return segmentNeedsFineWithLevel(levels_[0], segment);
  }

  template <typename Trajectory>
  double evaluateDiscreteAttractor(
      const Trajectory &trajectory,
      typename Trajectory::CoeffMat &grad_coefficients,
      Eigen::VectorXd &grad_durations) const
  {
    if (!discrete_attractor_active_)
    {
      return 0.0;
    }
    const double weight = penalty_weights_(4);
    const int junctions =
        std::min(trajectory.getPieceNum() - 1,
                 static_cast<int>(waypoint_attractors_->cols()));
    if (junctions <= 0 ||
        waypoint_attractor_dead_d_->size() < junctions)
    {
      return 0.0;
    }

    double cost = 0.0;
    const Eigen::VectorXd &durations = trajectory.getDurations();
    double absolute_time = 0.0;
    for (int junction = 0; junction < junctions; ++junction)
    {
      const double duration = durations(junction);
      if (!std::isfinite(duration) || duration <= 0.0)
      {
        continue;
      }
      absolute_time += duration;
      const auto position = trajectory.getPos(absolute_time);
      Eigen::Vector3d gradient = Eigen::Vector3d::Zero();
      cost += cost_functional::accumulateWaypointAttractorPenalty(
          position,
          waypoint_attractors_->col(junction),
          (*waypoint_attractor_dead_d_)(junction),
          smooth_eps_,
          weight,
          gradient,
          &hull_violation_(5));

      if (gradient.squaredNorm() <= 0.0)
      {
        continue;
      }

      const auto basis =
          Trajectory::derivativeBasis(0, duration);
      const int base_row = junction * Trajectory::COEFF_NUM;
      grad_coefficients
          .middleRows(base_row, Trajectory::COEFF_NUM)
          .noalias() += basis.transpose() * gradient.transpose();

      // Endpoint depends on duration through the power basis.
      const auto velocity = trajectory.getVel(absolute_time);
      grad_durations(junction) += gradient.dot(velocity);
    }
    return cost;
  }

  double accumulateSegmentPositionCost(
      LevelWorkspace &level,
      int segment,
      double duration,
      Eigen::VectorXd &direct_duration_gradients) const
  {
    const double weight = std::max(0.0, penalty_weights_(0));
    if (weight <= 0.0 || segment >= h_poly_idx_->size())
    {
      return 0.0;
    }
    const int poly_id = (*h_poly_idx_)(segment);
    if (poly_id < 0 || poly_id >= static_cast<int>(h_polys_->size()))
    {
      return 0.0;
    }

    const auto &poly = (*h_polys_)[poly_id];
    const int leaves = level.hull.piecesPerSegment();
    const int controls_per_piece = controlsPerPiece(level, 0);
    const double base_scale =
        duration / static_cast<double>(leaves * controls_per_piece);
    double cost = 0.0;

    std::vector<char> plane_active(static_cast<std::size_t>(poly.rows()), 0);
    for (int plane = 0; plane < poly.rows(); ++plane)
    {
      double max_raw = -std::numeric_limits<double>::infinity();
      for (int leaf = 0; leaf < leaves; ++leaf)
      {
        const int piece = segment * leaves + leaf;
        const int first_control = leaf == 0 ? 0 : 1;
        for (int control = first_control; control < controls_per_piece;
             ++control)
        {
          const int row = piece * controls_per_piece + control;
          const Eigen::Vector3d value =
              level.controls[0].row(row).transpose();
          const double raw =
              poly.template block<1, 3>(plane, 0).dot(value) +
              poly(plane, 3);
          max_raw = std::max(max_raw, raw);
        }
      }
      if (max_raw > -adaptive_.position_refine_margin)
      {
        plane_active[static_cast<std::size_t>(plane)] = 1;
      }
    }

    for (int leaf = 0; leaf < leaves; ++leaf)
    {
      const int piece = segment * leaves + leaf;
      const int first_control = leaf == 0 ? 0 : 1;
      for (int control = first_control; control < controls_per_piece;
           ++control)
      {
        const int row = piece * controls_per_piece + control;
        const double multiplicity =
            control == controls_per_piece - 1 && leaf + 1 < leaves ? 2.0
                                                                  : 1.0;
        const Eigen::Vector3d value =
            level.controls[0].row(row).transpose();
        Eigen::Vector3d gradient = Eigen::Vector3d::Zero();
        double local_cost = 0.0;
        for (int plane = 0; plane < poly.rows(); ++plane)
        {
          if (!plane_active[static_cast<std::size_t>(plane)])
          {
            continue;
          }
          const Eigen::Vector3d normal =
              poly.template block<1, 3>(plane, 0).transpose();
          ++last_scalar_constraint_checks_;
          const double raw = normal.dot(value) + poly(plane, 3);
          hull_violation_(1) = std::max(hull_violation_(1), raw);
          const double violation = raw / position_scale_;
          double penalty = 0.0;
          double penalty_grad = 0.0;
          if (cost_functional::smoothedL1(
                  violation, smooth_eps_, penalty, penalty_grad))
          {
            const double scale = weight * base_scale * multiplicity;
            gradient +=
                scale * penalty_grad / position_scale_ * normal;
            local_cost += scale * penalty;
          }
        }
        level.gradients[0].row(row) += gradient.transpose();
        direct_duration_gradients(segment) += local_cost / duration;
        cost += local_cost;
      }
    }
    return cost;
  }

  double accumulateSegmentDerivativeCost(
      LevelWorkspace &level,
      int segment,
      int derivative_order,
      double duration,
      Eigen::VectorXd &direct_duration_gradients) const
  {
    const double weight =
        std::max(0.0, penalty_weights_(derivative_order));
    const double bound = magnitude_bounds_(derivative_order - 1);
    if (weight <= 0.0 || !std::isfinite(bound) || bound <= 0.0)
    {
      return 0.0;
    }

    const int leaves = level.hull.piecesPerSegment();
    const int controls_per_piece =
        controlsPerPiece(level, derivative_order);
    const double base_scale =
        duration / static_cast<double>(leaves * controls_per_piece);
    double cost = 0.0;
    for (int leaf = 0; leaf < leaves; ++leaf)
    {
      const int piece = segment * leaves + leaf;
      const int first_control = leaf == 0 ? 0 : 1;
      for (int control = first_control; control < controls_per_piece;
           ++control)
      {
        const int row = piece * controls_per_piece + control;
        const double multiplicity =
            control == controls_per_piece - 1 && leaf + 1 < leaves ? 2.0
                                                                  : 1.0;
        ++last_scalar_constraint_checks_;
        const Eigen::Vector3d value =
            level.controls[derivative_order].row(row).transpose();
        Eigen::Vector3d gradient = Eigen::Vector3d::Zero();
        const double local_cost =
            cost_functional::accumulateSquaredNormBoundPenalty(
                value,
                bound * bound,
                smooth_eps_,
                weight * base_scale * multiplicity,
                gradient,
                &hull_violation_(derivative_order + 1));
        level.gradients[derivative_order].row(row) += gradient.transpose();
        direct_duration_gradients(segment) += local_cost / duration;
        cost += local_cost;
      }
    }
    return cost;
  }

  void backwardHodographs(LevelWorkspace &level,
                          const Eigen::VectorXd &durations,
                          Eigen::VectorXd &duration_gradients) const
  {
    const int leaves = level.hull.piecesPerSegment();
    for (int order = 3; order >= 1; --order)
    {
      const int current_cp = controlsPerPiece(level, order);
      const int previous_cp = current_cp + 1;
      const double degree_factor = static_cast<double>(previous_cp - 1);
      for (int piece = 0; piece < level.hull.numPieces(); ++piece)
      {
        const int segment = level.hull.pieceInfo(piece).source_segment;
        if (levelIndexForSegment(segment) !=
            (level.depth == 0 ? 0 : 1))
        {
          continue;
        }
        const double duration = durations(segment);
        const double scale =
            degree_factor * static_cast<double>(leaves) / duration;
        const int current_row = piece * current_cp;
        const int previous_row = piece * previous_cp;
        duration_gradients(segment) -=
            level.gradients[order]
                .middleRows(current_row, current_cp)
                .cwiseProduct(level.controls[order]
                                  .middleRows(current_row, current_cp))
                .sum() /
            duration;
        for (int control = 0; control < current_cp; ++control)
        {
          const auto gradient =
              level.gradients[order].row(current_row + control);
          level.gradients[order - 1].row(previous_row + control) -=
              scale * gradient;
          level.gradients[order - 1].row(previous_row + control + 1) +=
              scale * gradient;
        }
      }
    }
  }

  template <typename Trajectory>
  double evaluateCoefficientAdaptive(
      const Trajectory &trajectory,
      typename Trajectory::CoeffMat &grad_coefficients,
      Eigen::VectorXd &grad_durations) const
  {
    using Clock = std::chrono::steady_clock;
    const auto t_xform = Clock::now();
    updateSelectedLevels(trajectory);
    last_evaluator_timing_.transform_seconds +=
        std::chrono::duration<double>(Clock::now() - t_xform).count();
    last_evaluator_timing_.hodograph_seconds +=
        last_evaluator_timing_.transform_seconds;
    const Eigen::VectorXd &durations = trajectory.getDurations();
    double cost = 0.0;
    const auto t_pos = Clock::now();
    for (int segment = 0;
         segment < static_cast<int>(selected_depths_.size());
         ++segment)
    {
      auto &level = levels_[levelIndexForSegment(segment)];
      cost += accumulateSegmentPositionCost(
          level, segment, durations(segment), grad_durations);
    }
    last_evaluator_timing_.position_residual_seconds +=
        std::chrono::duration<double>(Clock::now() - t_pos).count();
    const auto t_der = Clock::now();
    for (int segment = 0;
         segment < static_cast<int>(selected_depths_.size());
         ++segment)
    {
      auto &level = levels_[levelIndexForSegment(segment)];
      for (int order = 1; order <= 3; ++order)
      {
        cost += accumulateSegmentDerivativeCost(
            level, segment, order, durations(segment), grad_durations);
      }
    }
    last_evaluator_timing_.derivative_residual_seconds +=
        std::chrono::duration<double>(Clock::now() - t_der).count();
    for (int level_index = 0; level_index < 2; ++level_index)
    {
      auto &level = levels_[level_index];
      if (!level.hull.kernel() || !levelSelected(level_index))
      {
        continue;
      }
      const auto t_rev = Clock::now();
      backwardHodographs(level, durations, grad_durations);
      last_evaluator_timing_.reverse_hodograph_seconds +=
          std::chrono::duration<double>(Clock::now() - t_rev).count();
      const auto t_add = Clock::now();
      level.hull.backwardAdd(level.gradients[0],
                             grad_coefficients,
                             grad_durations);
      last_evaluator_timing_.backward_add_seconds +=
          std::chrono::duration<double>(Clock::now() - t_add).count();
    }
    return cost;
  }

  int controlsPerPiece(int derivative_order) const
  {
    return bezier_hull_.sourceDegree() + 1 - derivative_order;
  }

  template <typename Trajectory>
  void updateControlPoints(const Trajectory &trajectory) const
  {
    const bool topology_changed =
        !bezier_hull_.kernel() ||
        bezier_hull_.numSourceSegments() != trajectory.getPieceNum() ||
        bezier_hull_.sourceNumCoeffs() != Trajectory::COEFF_NUM ||
        bezier_hull_.subdivisionDepth() != subdivision_depth_ ||
        cached_output_basis_ != basis_;
    if (topology_changed)
    {
      bezier_hull_.resetTopology(trajectory.getPieceNum(),
                                 Trajectory::COEFF_NUM,
                                 Basis::Bezier,
                                 0,
                                 subdivision_depth_);
      cached_output_basis_ = basis_;
      const int num_pieces = bezier_hull_.numPieces();
      for (int derivative_order = 0; derivative_order <= 3;
           ++derivative_order)
      {
        const int degree = bezier_hull_.sourceDegree() - derivative_order;
        const int cp = degree + 1;
        bezier_controls_[derivative_order].resize(num_pieces * cp, 3);
        selected_controls_[derivative_order].resize(num_pieces * cp, 3);
        bezier_gradients_[derivative_order].resize(num_pieces * cp, 3);
        selected_gradients_[derivative_order].resize(num_pieces * cp, 3);

        if (basis_ == Basis::Bezier)
        {
          basis_change_[derivative_order] =
              Eigen::MatrixXd::Identity(cp, cp);
        }
        else
        {
          const Eigen::MatrixXd bezier_power_to_control =
              Hull::powerToControlMatrix(Basis::Bezier, degree);
          const Eigen::MatrixXd minvo_power_to_control =
              Hull::powerToControlMatrix(Basis::MINVO, degree);
          basis_change_[derivative_order] =
              minvo_power_to_control *
              bezier_power_to_control.inverse();
        }
      }
    }

    trajectory.updateConvexHull(bezier_hull_);
    bezier_controls_[0] = bezier_hull_.controls();
    const Eigen::VectorXd &durations = trajectory.getDurations();
    const int leaves = bezier_hull_.piecesPerSegment();
    for (int derivative_order = 1; derivative_order <= 3;
         ++derivative_order)
    {
      const int previous_cp = controlsPerPiece(derivative_order - 1);
      const int current_cp = previous_cp - 1;
      const double degree_factor = static_cast<double>(previous_cp - 1);
      for (int piece = 0; piece < bezier_hull_.numPieces(); ++piece)
      {
        const int segment = bezier_hull_.pieceInfo(piece).source_segment;
        const double hodograph_scale =
            degree_factor * static_cast<double>(leaves) /
            durations(segment);
        const int previous_row = piece * previous_cp;
        const int current_row = piece * current_cp;
        for (int control = 0; control < current_cp; ++control)
        {
          bezier_controls_[derivative_order].row(current_row + control) =
              hodograph_scale *
              (bezier_controls_[derivative_order - 1]
                   .row(previous_row + control + 1) -
               bezier_controls_[derivative_order - 1]
                   .row(previous_row + control));
        }
      }
    }

    for (int derivative_order = 0; derivative_order <= 3;
         ++derivative_order)
    {
      const int cp = controlsPerPiece(derivative_order);
      if (basis_ == Basis::Bezier)
      {
        selected_controls_[derivative_order] =
            bezier_controls_[derivative_order];
      }
      else
      {
        for (int piece = 0; piece < bezier_hull_.numPieces(); ++piece)
        {
          selected_controls_[derivative_order]
              .middleRows(piece * cp, cp)
              .noalias() =
              basis_change_[derivative_order] *
              bezier_controls_[derivative_order]
                  .middleRows(piece * cp, cp);
        }
      }
      bezier_gradients_[derivative_order].setZero();
      selected_gradients_[derivative_order].setZero();
    }
  }

  void refineFlatnessCertificateControls() const
  {
    constexpr int extra_depth = 2;
    constexpr int extra_leaves = 1 << extra_depth;
    const int source_leaves = bezier_hull_.piecesPerSegment();
    flatness_certificate_leaves_per_segment_ =
        source_leaves * extra_leaves;
    for (int order = 1; order <= 3; ++order)
    {
      const int cp = controlsPerPiece(order);
      auto &refined = flatness_certificate_controls_[order];
      refined.resize(bezier_hull_.numSourceSegments() *
                         flatness_certificate_leaves_per_segment_ * cp,
                     3);
      for (int segment = 0;
           segment < bezier_hull_.numSourceSegments();
           ++segment)
      {
        for (int leaf = 0; leaf < source_leaves; ++leaf)
        {
          std::vector<Eigen::MatrixXd> current;
          current.emplace_back(
              bezier_controls_[order].middleRows(
                  (segment * source_leaves + leaf) * cp, cp));
          for (int depth = 0; depth < extra_depth; ++depth)
          {
            std::vector<Eigen::MatrixXd> next;
            next.reserve(current.size() * 2);
            for (const auto &controls : current)
            {
              const auto children =
                  traj_opt::convex_hull::deCasteljauSplit(controls, 0.5);
              next.push_back(children.first);
              next.push_back(children.second);
            }
            current.swap(next);
          }
          for (int child = 0; child < extra_leaves; ++child)
          {
            const int refined_leaf =
                leaf * extra_leaves + child;
            refined.middleRows(
                (segment * flatness_certificate_leaves_per_segment_ +
                 refined_leaf) *
                    cp,
                cp) = current[static_cast<std::size_t>(child)];
          }
        }
      }
    }
  }

  double accumulatePositionCost(
      const Eigen::VectorXd &durations,
      Eigen::VectorXd &direct_duration_gradients) const
  {
    if (basis_ == Basis::Bezier)
    {
      return accumulateBezierPositionCost(durations,
                                          direct_duration_gradients);
    }

    const double weight = std::max(0.0, penalty_weights_(0));
    if (weight <= 0.0)
    {
      return 0.0;
    }

    double cost = 0.0;
    const int controls_per_piece = controlsPerPiece(0);
    for (int piece = 0; piece < bezier_hull_.numPieces(); ++piece)
    {
      const int segment = bezier_hull_.pieceInfo(piece).source_segment;
      if (segment < 0 || segment >= h_poly_idx_->size())
      {
        continue;
      }
      const int poly_id = (*h_poly_idx_)(segment);
      if (poly_id < 0 || poly_id >= static_cast<int>(h_polys_->size()))
      {
        continue;
      }
      const double scale =
          durations(segment) /
          static_cast<double>(bezier_hull_.piecesPerSegment() *
                              controls_per_piece);
      for (int control = 0; control < controls_per_piece; ++control)
      {
        const int row = piece * controls_per_piece + control;
        const Eigen::Vector3d value =
            selected_controls_[0].row(row).transpose();
        Eigen::Vector3d gradient = Eigen::Vector3d::Zero();
        ++last_scalar_constraint_checks_;
        const double local_cost =
            cost_functional::accumulatePolytopePositionPenalty(
                (*h_polys_)[poly_id],
                value,
                smooth_eps_,
                weight * scale,
                gradient,
                &hull_violation_(1),
                position_scale_);
        selected_gradients_[0].row(row) += gradient.transpose();
        direct_duration_gradients(segment) +=
            local_cost / durations(segment);
        cost += local_cost;
      }
    }
    return cost;
  }

  double accumulateDerivativeCost(
      const Eigen::VectorXd &durations,
      int derivative_order,
      Eigen::VectorXd &direct_duration_gradients) const
  {
    if (basis_ == Basis::Bezier)
    {
      return accumulateBezierDerivativeCost(durations,
                                            derivative_order,
                                            direct_duration_gradients);
    }

    const double weight =
        std::max(0.0, penalty_weights_(derivative_order));
    const double bound = magnitude_bounds_(derivative_order - 1);
    if (weight <= 0.0 || !std::isfinite(bound) || bound <= 0.0)
    {
      return 0.0;
    }

    double cost = 0.0;
    const int controls_per_piece = controlsPerPiece(derivative_order);
    for (int piece = 0; piece < bezier_hull_.numPieces(); ++piece)
    {
      const int segment = bezier_hull_.pieceInfo(piece).source_segment;
      const double scale =
          durations(segment) /
          static_cast<double>(bezier_hull_.piecesPerSegment() *
                              controls_per_piece);
      for (int control = 0; control < controls_per_piece; ++control)
      {
        const int row = piece * controls_per_piece + control;
        ++last_scalar_constraint_checks_;
        const Eigen::Vector3d value =
            selected_controls_[derivative_order].row(row).transpose();
        Eigen::Vector3d gradient = Eigen::Vector3d::Zero();
        const double local_cost =
            cost_functional::accumulateSquaredNormBoundPenalty(
                value,
                bound * bound,
                smooth_eps_,
                weight * scale,
                gradient,
                &hull_violation_(derivative_order + 1));
        selected_gradients_[derivative_order].row(row) +=
            gradient.transpose();
        direct_duration_gradients(segment) +=
            local_cost / durations(segment);
        cost += local_cost;
      }
    }
    return cost;
  }

  double accumulateBezierPositionCost(
      const Eigen::VectorXd &durations,
      Eigen::VectorXd &direct_duration_gradients) const
  {
    const double weight = std::max(0.0, penalty_weights_(0));
    if (weight <= 0.0)
    {
      return 0.0;
    }

    double cost = 0.0;
    const int leaves = bezier_hull_.piecesPerSegment();
    const int controls_per_piece = controlsPerPiece(0);

    for (int segment = 0;
         segment < bezier_hull_.numSourceSegments();
         ++segment)
    {
      if (segment >= h_poly_idx_->size())
      {
        continue;
      }
      const int poly_id = (*h_poly_idx_)(segment);
      if (poly_id < 0 || poly_id >= static_cast<int>(h_polys_->size()))
      {
        continue;
      }
      const double duration = durations(segment);
      const double base_scale =
          duration /
          static_cast<double>(leaves * controls_per_piece);
      for (int leaf = 0; leaf < leaves; ++leaf)
      {
        const int piece = segment * leaves + leaf;
        const int first_control = leaf == 0 ? 0 : 1;
        for (int control = first_control;
             control < controls_per_piece;
             ++control)
        {
          const int row = piece * controls_per_piece + control;
          // The last control of every non-final leaf is exactly the first
          // control of the next leaf. Fold both identical V1 terms into this
          // row instead of evaluating the same penalty twice.
          const double multiplicity =
              control == controls_per_piece - 1 && leaf + 1 < leaves
                  ? 2.0
                  : 1.0;
          ++last_scalar_constraint_checks_;
          const Eigen::Vector3d value =
              selected_controls_[0].row(row).transpose();
          Eigen::Vector3d gradient = Eigen::Vector3d::Zero();
          const double local_cost =
              cost_functional::accumulatePolytopePositionPenalty(
                  (*h_polys_)[poly_id],
                  value,
                  smooth_eps_,
                  weight * base_scale * multiplicity,
                  gradient,
                  &hull_violation_(1),
                  position_scale_);
          selected_gradients_[0].row(row) += gradient.transpose();
          direct_duration_gradients(segment) += local_cost / duration;
          cost += local_cost;
        }
      }
    }
    return cost;
  }

  double accumulateBezierDerivativeCost(
      const Eigen::VectorXd &durations,
      int derivative_order,
      Eigen::VectorXd &direct_duration_gradients) const
  {
    const double weight =
        std::max(0.0, penalty_weights_(derivative_order));
    const double bound = magnitude_bounds_(derivative_order - 1);
    if (weight <= 0.0 || !std::isfinite(bound) || bound <= 0.0)
    {
      return 0.0;
    }

    double cost = 0.0;
    const int leaves = bezier_hull_.piecesPerSegment();
    const int controls_per_piece = controlsPerPiece(derivative_order);

    for (int segment = 0;
         segment < bezier_hull_.numSourceSegments();
         ++segment)
    {
      const double duration = durations(segment);
      const double base_scale =
          duration /
          static_cast<double>(leaves * controls_per_piece);
      for (int leaf = 0; leaf < leaves; ++leaf)
      {
        const int piece = segment * leaves + leaf;
        const int first_control = leaf == 0 ? 0 : 1;
        for (int control = first_control;
             control < controls_per_piece;
             ++control)
        {
          const int row = piece * controls_per_piece + control;
          const double multiplicity =
              control == controls_per_piece - 1 && leaf + 1 < leaves
                  ? 2.0
                  : 1.0;
          ++last_scalar_constraint_checks_;
          const Eigen::Vector3d value =
              selected_controls_[derivative_order].row(row).transpose();
          Eigen::Vector3d gradient = Eigen::Vector3d::Zero();
          const double local_cost =
              cost_functional::accumulateSquaredNormBoundPenalty(
                  value,
                  bound * bound,
                  smooth_eps_,
                  weight * base_scale * multiplicity,
                  gradient,
                  &hull_violation_(derivative_order + 1));
          selected_gradients_[derivative_order].row(row) +=
              gradient.transpose();
          direct_duration_gradients(segment) += local_cost / duration;
          cost += local_cost;
        }
      }
    }
    return cost;
  }

  double accumulateFlatnessCost() const
  {
    if (!flatness_enabled_ || !flatness_cost_.referenceReady() ||
        !bezier_hull_.kernel())
    {
      return 0.0;
    }
    const int pieces = bezier_hull_.numPieces();
    const int vel_cp = controlsPerPiece(1);
    const int acc_cp = controlsPerPiece(2);
    const int jerk_cp = controlsPerPiece(3);
    last_scalar_constraint_checks_ +=
        static_cast<std::size_t>(pieces * vel_cp);
    // Physics is on Bezier hodograph controls; write into selected_
    // gradients (identical for Bezier) so reverse-hodograph stays unified.
    return flatness_cost_.accumulate(bezier_controls_[1],
                                     bezier_controls_[2],
                                     bezier_controls_[3],
                                     pieces,
                                     vel_cp,
                                     acc_cp,
                                     jerk_cp,
                                     selected_gradients_[1],
                                     selected_gradients_[2],
                                     selected_gradients_[3]);
  }

  void backwardControlPointGradients(
      const Eigen::VectorXd &durations,
      Eigen::VectorXd &direct_duration_gradients) const
  {
    for (int derivative_order = 0; derivative_order <= 3;
         ++derivative_order)
    {
      const int cp = controlsPerPiece(derivative_order);
      if (basis_ == Basis::Bezier)
      {
        bezier_gradients_[derivative_order] =
            selected_gradients_[derivative_order];
      }
      else
      {
        for (int piece = 0; piece < bezier_hull_.numPieces(); ++piece)
        {
          bezier_gradients_[derivative_order]
              .middleRows(piece * cp, cp)
              .noalias() =
              basis_change_[derivative_order].transpose() *
              selected_gradients_[derivative_order]
                  .middleRows(piece * cp, cp);
        }
      }
    }

    const int leaves = bezier_hull_.piecesPerSegment();
    for (int derivative_order = 3; derivative_order >= 1;
         --derivative_order)
    {
      const int current_cp = controlsPerPiece(derivative_order);
      const int previous_cp = current_cp + 1;
      const double degree_factor = static_cast<double>(previous_cp - 1);
      for (int piece = 0; piece < bezier_hull_.numPieces(); ++piece)
      {
        const int segment = bezier_hull_.pieceInfo(piece).source_segment;
        const double duration = durations(segment);
        const double hodograph_scale =
            degree_factor * static_cast<double>(leaves) / duration;
        const int current_row = piece * current_cp;
        const int previous_row = piece * previous_cp;

        direct_duration_gradients(segment) -=
            bezier_gradients_[derivative_order]
                .middleRows(current_row, current_cp)
                .cwiseProduct(bezier_controls_[derivative_order]
                                  .middleRows(current_row, current_cp))
                .sum() /
            duration;

        for (int control = 0; control < current_cp; ++control)
        {
          const auto gradient =
              bezier_gradients_[derivative_order]
                  .row(current_row + control);
          bezier_gradients_[derivative_order - 1]
              .row(previous_row + control) -= hodograph_scale * gradient;
          bezier_gradients_[derivative_order - 1]
              .row(previous_row + control + 1) += hodograph_scale * gradient;
        }
      }
    }
  }

  ExpIntegralCostManager residual_cost_manager_;
  const general_utils::PolyhedraH *h_polys_{nullptr};
  const Eigen::VectorXi *h_poly_idx_{nullptr};
  const general_utils::Mat3Df *waypoint_attractors_{nullptr};
  const general_utils::VecDf *waypoint_attractor_dead_d_{nullptr};
  double smooth_eps_{1.0e-3};
  double position_scale_{0.25};
  double robust_certificate_margin_{0.05};
  general_utils::VecDf magnitude_bounds_;
  general_utils::VecDf penalty_weights_;
  Basis basis_{Basis::Bezier};
  mutable Basis cached_output_basis_{Basis::Bezier};
  int subdivision_depth_{0};
  bool dense_sampling_required_{true};
  bool discrete_attractor_active_{false};
  bool flatness_enabled_{false};
  bool flatness_advisory_only_{false};
  mutable FlatnessCost flatness_cost_{};
  LegacyAdaptiveOptions adaptive_{};
  mutable std::array<LevelWorkspace, 2> levels_{};
  mutable std::vector<int> selected_depths_;
  mutable std::size_t last_scalar_constraint_checks_{0};
  mutable bool last_coarse_screen_only_{false};
  mutable EvaluatorTiming last_evaluator_timing_{};

  mutable Hull bezier_hull_;
  mutable std::array<Eigen::MatrixXd, 4> basis_change_;
  mutable std::array<HullMatrix, 4> bezier_controls_;
  mutable std::array<HullMatrix, 4> selected_controls_;
  mutable std::array<HullMatrix, 4> bezier_gradients_;
  mutable std::array<HullMatrix, 4> selected_gradients_;
  mutable std::array<HullMatrix, 4> flatness_certificate_controls_;
  mutable int flatness_certificate_leaves_per_segment_{1};
  mutable general_utils::VecDf hull_violation_{
      general_utils::VecDf::Zero(9)};
  mutable general_utils::VecDf combined_penalty_log_{
      general_utils::VecDf::Zero(9)};
};
} // namespace cost_functional_manager

#endif
